import { afterEach, expect, it, vi } from "vitest";
import { OutlineDisplayController } from "../src/ui/outline_display_controller.svelte.ts";
import { OutlineFocusAdapter } from "../src/ui/outline_focus_adapter.ts";
import { EMPTY_OUTLINE_FILTER } from "../src/services/outline_filter.ts";
afterEach(() => vi.useRealTimers());
it("keeps live conditions independent of captured restoration values", () => {
	const display = new OutlineDisplayController();
	const ids = ["a", "a", "b"];
	display.setExpanded(ids);
	ids.push("c");
	expect(display.expanded).toEqual(["a", "b"]);
	display.clearExpansion("a");
	display.expand("b");
	expect(display.expanded).toEqual(["b"]);
	display.clearFilter();
	expect(display.filter).toEqual(EMPTY_OUTLINE_FILTER);
});
it("invalidates scheduled focus on pane, receipt, navigation and disposal", () => {
	vi.useFakeTimers();
	let context = { pane: "a", origin: 1 };
	let current = true;
	const focus = vi.fn();
	const adapter = new OutlineFocusAdapter({ context: () => context, canFocus: () => true, focus });
	adapter.request("x", 3, () => current);
	context = { pane: "b", origin: 1 };
	vi.runAllTimers();
	adapter.request("x", 3, () => current);
	context = { pane: "b", origin: 2 };
	vi.runAllTimers();
	adapter.request("x", 3, () => current);
	current = false;
	vi.runAllTimers();
	expect(focus).not.toHaveBeenCalled();
	current = true;
	adapter.request("x", 3, () => current);
	vi.runAllTimers();
	expect(focus).toHaveBeenCalledWith("x", 3);
	adapter.request("x", 4, () => current);
	adapter.dispose();
	vi.runAllTimers();
	expect(focus).toHaveBeenCalledTimes(1);
});
