import { assertEquals, assertFalse } from "jsr:@std/assert@1";
import { DEFAULT_UI_VOCABULARY, type UiEntityCode } from "../src/shared/ui_vocabulary.ts";

Deno.test("default UI vocabulary covers every semantic entity code with neutral labels", () => {
	const codes: UiEntityCode[] = [
		"work",
		"occurrence",
		"semanticLink",
		"workingCopy",
		"revision",
		"branch",
		"merge",
		"globalLineage",
		"workLineage",
		"recoverySnapshot",
		"tag",
		"bookmark",
		"resumePosition",
		"today",
		"quickCapture",
		"unplacedInbox",
		"hoist",
		"breadcrumb",
		"browsingHistory",
		"pane",
		"query",
		"commandPalette",
		"advancedLinkEditor",
		"linkSource",
		"linkType",
		"linkTarget",
		"directionPreview",
		"internalReference",
		"backlink",
		"comparisonPane",
		"comparisonLeft",
		"comparisonRight",
		"comparisonReason",
		"fixedRevision",
		"comparisonAdded",
		"comparisonRemoved",
		"comparisonUnchanged",
		"unknownTime",
		"markdownEditor",
		"editorMode",
		"editorNormal",
		"editorPlain",
		"editorPreview",
		"sparseOutline",
		"queryResult",
		"noQueryResult",
		"stub",
		"stubList",
		"stubContext",
		"duplicateCandidates",
		"duplicateReason",
		"duplicateScore",
		"duplicateCandidateHint",
		"duplicateCandidateActions",
		"duplicateMerge",
		"duplicateKeepLeft",
		"duplicateKeepRight",
		"duplicateCreateLike",
		"duplicateCreateRelated",
		"duplicateDismiss",
		"duplicateMergeConfirm",
		"emergenceLoading",
		"emergenceAccept",
		"emergenceHold",
		"emergenceDismiss",
		"emergenceResolutionReason",
		"noEmergenceSuggestion",
		"manuscript",
		"manuscriptOpen",
		"manuscriptTotalCount",
		"manuscriptBranchCount",
		"manuscriptReadOnly",
		"markdownExportMode",
		"markdownExportSettings",
		"markdownExportScope",
		"markdownExportAll",
		"markdownExportSelected",
		"markdownExportAdvanced",
		"markdownExportAncestors",
		"markdownExportDescendants",
		"markdownExportSemanticNeighbors",
		"markdownExportSelectionRequired",
		"markdownExportAction",
		"markdownExportRadiora",
		"markdownExportPortable",
		"markdownExportObsidian",
		"opmlExport",
		"opmlImport",
		"opmlExportSuccess",
		"opmlImportSuccess",
		"jsonBackupExport",
		"jsonBackupExportSuccess",
		"jsonBackupRestore",
		"jsonBackupRestoreSuccess",
		"jsonBackupRestoreFailureRecovery",
	];
	assertEquals(Object.keys(DEFAULT_UI_VOCABULARY).sort(), [...codes].sort());
	assertFalse(Object.values(DEFAULT_UI_VOCABULARY).some((label) => /実身|化身/.test(label)));
	assertEquals(DEFAULT_UI_VOCABULARY, {
		work: "項目",
		occurrence: "配置",
		semanticLink: "意味関係",
		workingCopy: "作業中の本文",
		revision: "版",
		branch: "別稿",
		merge: "混成稿",
		globalLineage: "全体系統",
		workLineage: "版系統",
		recoverySnapshot: "復元用保存",
		tag: "タグ",
		bookmark: "栞",
		resumePosition: "作業再開位置",
		today: "今日",
		quickCapture: "クイック入力",
		unplacedInbox: "未配置箱",
		hoist: "絞り込み表示",
		breadcrumb: "祖先",
		browsingHistory: "閲覧履歴",
		pane: "ペイン",
		query: "Query",
		commandPalette: "コマンドパレット",
		advancedLinkEditor: "高度な意味関係編集",
		linkSource: "起点",
		linkType: "種別",
		linkTarget: "終点",
		directionPreview: "保存方向",
		internalReference: "内部参照",
		backlink: "被参照",
		comparisonPane: "比較",
		comparisonLeft: "左",
		comparisonRight: "右",
		comparisonReason: "理由",
		fixedRevision: "固定版",
		comparisonAdded: "追加",
		comparisonRemoved: "削除",
		comparisonUnchanged: "変更なし",
		unknownTime: "日時不明",
		markdownEditor: "Markdown編集",
		editorMode: "表示",
		editorNormal: "通常",
		editorPlain: "Markdown",
		editorPreview: "プレビュー",
		sparseOutline: "投影表示",
		queryResult: "結果",
		noQueryResult: "一致する項目はありません",
		stub: "Stub",
		stubList: "Stub一覧",
		stubContext: "作成文脈",
		duplicateCandidates: "重複候補",
		duplicateReason: "根拠",
		duplicateScore: "スコア",
		duplicateCandidateHint:
			"項目のタイトル・検索別名・タグ・意味関係の一致を根拠に、操作を選べます。候補が自動採用されることはありません。",
		duplicateCandidateActions: "重複候補の操作",
		duplicateMerge: "統合する",
		duplicateKeepLeft: "左の項目を残す",
		duplicateKeepRight: "右の項目を残す",
		duplicateCreateLike: "LIKEを作成",
		duplicateCreateRelated: "RELATEDを作成",
		duplicateDismiss: "却下（何もしない）",
		duplicateMergeConfirm: "項目を統合しますか？",
		emergenceLoading: "関係を探索中…",
		emergenceAccept: "採用",
		emergenceHold: "保留",
		emergenceDismiss: "却下",
		emergenceResolutionReason: "判断理由（却下時は必須）",
		noEmergenceSuggestion: "新しい関係候補はありません",
		manuscript: "原稿",
		manuscriptOpen: "原稿として開く",
		manuscriptTotalCount: "全体文字数",
		manuscriptBranchCount: "枝の文字数",
		manuscriptReadOnly: "固定版のため読み取り専用",
		markdownExportMode: "Markdown参照形式",
		markdownExportSettings: "Markdown書き出し設定",
		markdownExportScope: "書き出す範囲",
		markdownExportAll: "アウトライン全体",
		markdownExportSelected: "選択した項目を基準",
		markdownExportAdvanced: "高度な範囲設定",
		markdownExportAncestors: "同じアウトラインの祖先を含める",
		markdownExportDescendants: "配下の項目をすべて含める",
		markdownExportSemanticNeighbors: "直接の意味関係でつながる項目を含める",
		markdownExportSelectionRequired: "選択した項目を基準にするには、項目を選択してください。",
		markdownExportAction: "Markdownでエクスポート",
		markdownExportRadiora: "Radiora（内部参照を保持）",
		markdownExportPortable: "ポータブル（表示名のみ）",
		markdownExportObsidian: "Obsidian（Wikiリンク）",
		opmlExport: "OPMLを書き出す",
		opmlImport: "OPMLを取り込む",
		opmlExportSuccess: "OPMLを書き出しました",
		opmlImportSuccess: "OPMLを取り込みました",
		jsonBackupExport: "完全バックアップを書き出す",
		jsonBackupExportSuccess: "完全バックアップを書き出しました",
		jsonBackupRestore: "完全バックアップから復元",
		jsonBackupRestoreSuccess: "完全バックアップを復元しました",
		jsonBackupRestoreFailureRecovery:
			"現在のデータは変更されていません。空き容量とファイル内容を確認して、もう一度お試しください。",
	});
});
