export type UiEntityCode =
	| "work"
	| "occurrence"
	| "semanticLink"
	| "workingCopy"
	| "revision"
	| "branch"
	| "merge"
	| "globalLineage"
	| "workLineage"
	| "recoverySnapshot"
	| "tag"
	| "bookmark"
	| "resumePosition"
	| "today"
	| "quickCapture"
	| "unplacedInbox"
	| "hoist"
	| "breadcrumb"
	| "browsingHistory"
	| "pane"
	| "query"
	| "commandPalette"
	| "advancedLinkEditor"
	| "linkSource"
	| "linkType"
	| "linkTarget"
	| "directionPreview"
	| "internalReference"
	| "backlink"
	| "comparisonPane"
	| "comparisonLeft"
	| "comparisonRight"
	| "comparisonReason"
	| "fixedRevision"
	| "comparisonAdded"
	| "comparisonRemoved"
	| "comparisonUnchanged"
	| "unknownTime"
	| "markdownEditor"
	| "editorMode"
	| "editorNormal"
	| "editorPlain"
	| "editorPreview"
	| "sparseOutline"
	| "queryResult"
	| "noQueryResult";

export type UiVocabulary = Readonly<Record<UiEntityCode, string>>;

export const DEFAULT_UI_VOCABULARY: UiVocabulary = Object.freeze({
	work: "項目",
	occurrence: "配置",
	semanticLink: "リンク",
	workingCopy: "作業中の本文",
	revision: "版",
	branch: "別稿",
	merge: "混成稿",
	globalLineage: "全体系統",
	workLineage: "版系統",
	recoverySnapshot: "復元用保存",
	tag: "タグ",
	bookmark: "栞",
	resumePosition: "作業再開位置",
	today: "今日",
	quickCapture: "クイック入力",
	unplacedInbox: "未配置箱",
	hoist: "絞り込み表示",
	breadcrumb: "祖先",
	browsingHistory: "閲覧履歴",
	pane: "ペイン",
	query: "Query",
	commandPalette: "コマンドパレット",
	advancedLinkEditor: "高度なリンク編集",
	linkSource: "起点",
	linkType: "種別",
	linkTarget: "終点",
	directionPreview: "保存方向",
	internalReference: "内部参照",
	backlink: "被参照",
	comparisonPane: "比較",
	comparisonLeft: "左",
	comparisonRight: "右",
	comparisonReason: "理由",
	fixedRevision: "固定版",
	comparisonAdded: "追加",
	comparisonRemoved: "削除",
	comparisonUnchanged: "変更なし",
	unknownTime: "日時不明",
	markdownEditor: "Markdown編集",
	editorMode: "表示",
	editorNormal: "通常",
	editorPlain: "Markdown",
	editorPreview: "プレビュー",
	sparseOutline: "投影表示",
	queryResult: "結果",
	noQueryResult: "一致する項目はありません",
});
