export const SURREAL_SCHEMA_DDL = `
	DEFINE TABLE IF NOT EXISTS relation_type_definition SCHEMAFULL;
	DEFINE FIELD IF NOT EXISTS name ON relation_type_definition TYPE string;
	DEFINE FIELD IF NOT EXISTS direction ON relation_type_definition TYPE string;
	DEFINE FIELD IF NOT EXISTS built_in ON relation_type_definition TYPE bool DEFAULT false;
	DEFINE FIELD IF NOT EXISTS created_at ON relation_type_definition TYPE string;
	DEFINE INDEX IF NOT EXISTS relation_type_definition_name ON relation_type_definition FIELDS name UNIQUE;
	DEFINE TABLE IF NOT EXISTS outline_item SCHEMAFULL;
	DEFINE FIELD IF NOT EXISTS text ON outline_item TYPE string;
	DEFINE FIELD IF NOT EXISTS order_key ON outline_item TYPE number;
	DEFINE FIELD IF NOT EXISTS collapsed ON outline_item TYPE bool DEFAULT false;
	DEFINE FIELD IF NOT EXISTS created_at ON outline_item TYPE string;
	DEFINE FIELD IF NOT EXISTS updated_at ON outline_item TYPE string;
	DEFINE FIELD IF NOT EXISTS title ON outline_item TYPE string DEFAULT "";
	DEFINE FIELD IF NOT EXISTS title_key ON outline_item TYPE string DEFAULT "";
	DEFINE FIELD IF NOT EXISTS title_prefix ON outline_item TYPE string DEFAULT "";
	DEFINE FIELD IF NOT EXISTS search_terms ON outline_item TYPE string DEFAULT "";
	DEFINE TABLE IF NOT EXISTS evolved_from TYPE RELATION IN outline_item OUT outline_item SCHEMAFULL;
	DEFINE TABLE IF NOT EXISTS liked TYPE RELATION IN outline_item OUT outline_item SCHEMAFULL;
	DEFINE TABLE IF NOT EXISTS fixed TYPE RELATION IN outline_item OUT outline_item SCHEMAFULL;
	DEFINE TABLE IF NOT EXISTS conflicted TYPE RELATION IN outline_item OUT outline_item SCHEMAFULL;
	DEFINE TABLE IF NOT EXISTS in_knot TYPE RELATION IN outline_item OUT outline_item SCHEMAFULL;
	DEFINE FIELD IF NOT EXISTS created_at ON liked TYPE string;
	DEFINE FIELD IF NOT EXISTS created_at ON fixed TYPE string;
	DEFINE FIELD IF NOT EXISTS created_at ON conflicted TYPE string;
	DEFINE FIELD IF NOT EXISTS created_at ON in_knot TYPE string;
	DEFINE TABLE IF NOT EXISTS knot SCHEMAFULL;
	DEFINE FIELD IF NOT EXISTS cycle_ids ON knot TYPE array<string>;
	DEFINE FIELD IF NOT EXISTS created_at ON knot TYPE string;
	DEFINE TABLE IF NOT EXISTS search_alias SCHEMAFULL;
	DEFINE FIELD IF NOT EXISTS canonical ON search_alias TYPE string;
	DEFINE FIELD IF NOT EXISTS variants ON search_alias TYPE array<string>;
	DEFINE FIELD IF NOT EXISTS created_at ON search_alias TYPE string;
	DEFINE FIELD IF NOT EXISTS updated_at ON search_alias TYPE string;
	DEFINE TABLE IF NOT EXISTS emergence_feedback SCHEMAFULL;
	DEFINE FIELD IF NOT EXISTS action ON emergence_feedback TYPE string;
	DEFINE FIELD IF NOT EXISTS updated_at ON emergence_feedback TYPE string;
	DEFINE TABLE IF NOT EXISTS emergence_suggestion SCHEMAFULL;
	DEFINE FIELD IF NOT EXISTS kind ON emergence_suggestion TYPE string;
	DEFINE FIELD IF NOT EXISTS context_work ON emergence_suggestion TYPE record<work>;
	DEFINE FIELD IF NOT EXISTS target_work ON emergence_suggestion TYPE record<work>;
	DEFINE FIELD IF NOT EXISTS context_occurrence_id ON emergence_suggestion TYPE string;
	DEFINE FIELD IF NOT EXISTS target_occurrence_id ON emergence_suggestion TYPE string;
	DEFINE FIELD IF NOT EXISTS proposed_link_type ON emergence_suggestion TYPE option<string>;
	DEFINE FIELD IF NOT EXISTS title ON emergence_suggestion TYPE string;
	DEFINE FIELD IF NOT EXISTS explanation ON emergence_suggestion TYPE string;
	DEFINE FIELD IF NOT EXISTS evidence ON emergence_suggestion TYPE array<object>;
	DEFINE FIELD IF NOT EXISTS evidence.*.fromId ON emergence_suggestion TYPE string;
	DEFINE FIELD IF NOT EXISTS evidence.*.toId ON emergence_suggestion TYPE string;
	DEFINE FIELD IF NOT EXISTS evidence.*.relation ON emergence_suggestion TYPE string;
	DEFINE FIELD IF NOT EXISTS score ON emergence_suggestion TYPE number;
	DEFINE FIELD IF NOT EXISTS status ON emergence_suggestion TYPE string;
	DEFINE FIELD IF NOT EXISTS created_at ON emergence_suggestion TYPE string;
	DEFINE FIELD IF NOT EXISTS updated_at ON emergence_suggestion TYPE string;
	DEFINE FIELD IF NOT EXISTS resolved_at ON emergence_suggestion TYPE option<string>;
	DEFINE FIELD IF NOT EXISTS resolution_reason ON emergence_suggestion TYPE option<string>;
	DEFINE TABLE IF NOT EXISTS saved_rule_query SCHEMAFULL;
	DEFINE FIELD IF NOT EXISTS name ON saved_rule_query TYPE string;
	DEFINE FIELD IF NOT EXISTS source ON saved_rule_query TYPE string;
	DEFINE FIELD IF NOT EXISTS created_at ON saved_rule_query TYPE string;
	DEFINE FIELD IF NOT EXISTS updated_at ON saved_rule_query TYPE string;
	DEFINE TABLE IF NOT EXISTS schema_metadata SCHEMAFULL;
	DEFINE FIELD IF NOT EXISTS version ON schema_metadata TYPE number;
	DEFINE FIELD IF NOT EXISTS updated_at ON schema_metadata TYPE string;
	DEFINE FIELD IF NOT EXISTS last_migration_id ON schema_metadata TYPE string;
	DEFINE FIELD IF NOT EXISTS app_version ON schema_metadata TYPE string;
	DEFINE TABLE IF NOT EXISTS migration_journal SCHEMAFULL;
	DEFINE FIELD IF NOT EXISTS from_version ON migration_journal TYPE number;
	DEFINE FIELD IF NOT EXISTS to_version ON migration_journal TYPE number;
	DEFINE FIELD IF NOT EXISTS started_at ON migration_journal TYPE string;
	DEFINE FIELD IF NOT EXISTS completed_at ON migration_journal TYPE option<string>;
	DEFINE FIELD IF NOT EXISTS app_version ON migration_journal TYPE string;
	DEFINE FIELD IF NOT EXISTS status ON migration_journal TYPE string;
	DEFINE FIELD IF NOT EXISTS error ON migration_journal TYPE option<string>;
	DEFINE ANALYZER IF NOT EXISTS title_prefix FILTERS lowercase, edgengram(1,64);
	DEFINE ANALYZER IF NOT EXISTS lexical TOKENIZERS class, camel, punct FILTERS lowercase;
	DEFINE ANALYZER IF NOT EXISTS japanese_terms TOKENIZERS blank FILTERS lowercase;
	DEFINE INDEX IF NOT EXISTS outline_title_prefix ON outline_item FIELDS title_prefix
		FULLTEXT ANALYZER title_prefix;
	DEFINE INDEX IF NOT EXISTS outline_title_lexical ON outline_item FIELDS title_key
		FULLTEXT ANALYZER lexical BM25;
	DEFINE INDEX IF NOT EXISTS outline_text_lexical ON outline_item FIELDS text
		FULLTEXT ANALYZER lexical BM25;
	DEFINE INDEX IF NOT EXISTS outline_terms_lexical ON outline_item FIELDS search_terms
		FULLTEXT ANALYZER japanese_terms BM25;
`;
